import os
from unittest.mock import MagicMock, patch

import pytest

from ai_engine import (BlueprintError, _parse_json_response,
                       generate_blueprint, render_blueprint_html,
                       render_blueprint_markdown, render_blueprint_pdf,
                       render_blueprint_text, sanitize_filename)

VALID_BLUEPRINT_DATA = {
    "project_name": "Test Project",
    "tech_stack": ["Python", "Streamlit"],
    "folder_structure": "app.py\nrequirements.txt",
    "edge_cases": ["Network timeout", "Invalid input"],
    "roadmap": ["Step 1", "Step 2", "Step 3", "Step 4", "Step 5"],
    "summary": "A test summary.",
}


def test_parse_plain_json():
    import json

    raw = json.dumps(VALID_BLUEPRINT_DATA)
    res = _parse_json_response(raw)
    assert res["project_name"] == "Test Project"
    assert res["tech_stack"] == ["Python", "Streamlit"]


def test_parse_fenced_json():
    import json

    raw = "```json\n" + json.dumps(VALID_BLUEPRINT_DATA) + "\n```"
    res = _parse_json_response(raw)
    assert res["project_name"] == "Test Project"


def test_parse_json_buried_in_prose():
    import json

    raw = (
        "Here is your requested system blueprint:\n```json\n"
        + json.dumps(VALID_BLUEPRINT_DATA)
        + "\n```\nHope this helps!"
    )
    res = _parse_json_response(raw)
    assert res["project_name"] == "Test Project"
    assert len(res["roadmap"]) == 5


def test_parse_invalid_json():
    with pytest.raises(BlueprintError):
        _parse_json_response("Not a json string at all")


def test_parse_missing_keys():
    import json

    incomplete = {"project_name": "Incomplete"}
    raw = json.dumps(incomplete)
    with pytest.raises(BlueprintError, match="Missing required blueprint key"):
        _parse_json_response(raw)


def test_parse_invalid_types():
    import json

    invalid_type_data = VALID_BLUEPRINT_DATA.copy()
    invalid_type_data["tech_stack"] = "not-a-list"
    raw = json.dumps(invalid_type_data)
    with pytest.raises(BlueprintError, match="Invalid type for tech_stack"):
        _parse_json_response(raw)


@patch.dict(os.environ, {}, clear=True)
def test_generate_blueprint_no_keys_raises_error():
    """Ensure zero network calls and BlueprintError when no API keys are present."""
    analysis = {"project_name": "No Key Test", "problem": "Test"}
    with pytest.raises(BlueprintError, match="All AI providers failed"):
        generate_blueprint(analysis)


@patch("ai_engine.requests.post")
@patch.dict(
    os.environ,
    {"GROQ_API_KEY": "fake_groq_key", "GEMINI_API_KEY": "fake_gemini_key"},
    clear=True,
)
def test_fallback_triggering(mock_post):
    import json

    # Groq tries 2 models, both fail. Then Gemini succeeds.
    success_resp = MagicMock()
    success_resp.status_code = 200
    success_resp.json.return_value = {
        "candidates": [
            {"content": {"parts": [{"text": json.dumps(VALID_BLUEPRINT_DATA)}]}}
        ]
    }

    mock_post.side_effect = [
        Exception("Groq model 1 error"),
        Exception("Groq model 2 error"),
        success_resp,
    ]

    analysis = {"project_name": "Fallback Test", "problem": "Test"}
    res = generate_blueprint(analysis)
    assert res["project_name"] == "Test Project"
    assert mock_post.call_count == 3


def test_render_blueprint_markdown_success():
    sample_blueprint = {
        "project_name": "Sample SaaS App",
        "tech_stack": ["Python", "Streamlit", "Supabase"],
        "folder_structure": "app.py\nrequirements.txt\nsupabase_client.py",
        "edge_cases": ["Rate limiting", "Auth timeout"],
        "roadmap": ["Design DB", "Setup Auth", "Build UI", "Add Tests", "Deploy"],
        "summary": "A robust SaaS application.",
    }
    md = render_blueprint_markdown(sample_blueprint, export_date="2026-03-30")
    assert "# Sample SaaS App" in md
    assert "## Summary" in md
    assert "A robust SaaS application." in md
    assert "## Tech Stack" in md
    assert "- Python" in md
    assert "## Folder Structure" in md
    assert "```text\napp.py" in md
    assert "```" in md
    assert "## Edge Cases & Risks" in md
    assert "- Rate limiting" in md
    assert "## Implementation Roadmap" in md
    assert "1. Design DB" in md
    assert "5. Deploy" in md
    assert "Generated by CodeBreaker v0.4 + 2026-03-30" in md


def test_render_blueprint_markdown_none_values():
    """Assert None values never leak as 'None' in rendered markdown."""
    bad_blueprint = {
        "project_name": None,
        "tech_stack": [None, "Python", None],
        "folder_structure": None,
        "edge_cases": None,
        "roadmap": [None],
        "summary": None,
    }
    md = render_blueprint_markdown(bad_blueprint)
    assert "# Untitled Project" in md
    assert "No summary provided." in md
    words = [w for line in md.split("\n") for w in line.split() if w == "None"]
    assert len(words) == 0


def test_sanitize_filename():
    assert sanitize_filename("My Project v1.0") == "my_project_v10_blueprint.md"
    assert sanitize_filename("../../etc/passwd") == "etcpasswd_blueprint.md"
    assert sanitize_filename("   ") == "codebreaker_blueprint.md"
    assert sanitize_filename(None) == "codebreaker_blueprint.md"
    assert sanitize_filename("Project: Name #1?*") == "project_name_1_blueprint.md"


def test_render_blueprint_text_success():
    sample_blueprint = {
        "project_name": "Sample SaaS App",
        "tech_stack": ["Python", "Streamlit", "Supabase"],
        "folder_structure": "app.py\nrequirements.txt\nsupabase_client.py",
        "edge_cases": ["Rate limiting", "Auth timeout"],
        "roadmap": ["Design DB", "Setup Auth", "Build UI", "Add Tests", "Deploy"],
        "summary": "A robust SaaS application.",
    }
    txt = render_blueprint_text(sample_blueprint, export_date="2026-03-30")
    assert "PROJECT: Sample SaaS App" in txt
    assert "SUMMARY" in txt
    assert "A robust SaaS application." in txt
    assert "TECH STACK" in txt
    assert "- Python" in txt
    assert "FOLDER STRUCTURE" in txt
    assert "app.py" in txt
    assert "EDGE CASES & RISKS" in txt
    assert "- Rate limiting" in txt
    assert "IMPLEMENTATION ROADMAP" in txt
    assert "1. Design DB" in txt
    assert "5. Deploy" in txt
    assert "Generated by CodeBreaker v0.4.1 + 2026-03-30" in txt
    for secret in ["GROQ_API_KEY", "GEMINI_API_KEY", "sk-", "AIza"]:
        assert secret not in txt


def test_render_blueprint_html_success():
    sample_blueprint = {
        "project_name": "Sample SaaS App",
        "tech_stack": ["Python", "Streamlit", "Supabase"],
        "folder_structure": "app.py\nrequirements.txt\nsupabase_client.py",
        "edge_cases": ["Rate limiting", "Auth timeout"],
        "roadmap": ["Design DB", "Setup Auth", "Build UI", "Add Tests", "Deploy"],
        "summary": "A robust SaaS application.",
    }
    html = render_blueprint_html(sample_blueprint, export_date="2026-03-30")
    assert "<!DOCTYPE html>" in html
    assert "<html" in html
    assert "</html>" in html
    assert "<body>" in html
    assert "</body>" in html
    assert "<title>Sample SaaS App - CodeBreaker System Blueprint</title>" in html
    assert "<h1>Sample SaaS App</h1>" in html
    assert "<h2>Summary</h2>" in html
    assert "A robust SaaS application." in html
    assert "<h2>Tech Stack</h2>" in html
    assert "Python" in html
    assert "Generated by CodeBreaker" in html
    for secret in ["GROQ_API_KEY", "GEMINI_API_KEY", "sk-", "AIza"]:
        assert secret not in html


def test_render_blueprint_pdf_success():
    sample_blueprint = {
        "project_name": "Sample SaaS App",
        "tech_stack": ["Python", "Streamlit", "Supabase"],
        "folder_structure": "app.py\nrequirements.txt\nsupabase_client.py",
        "edge_cases": ["Rate limiting", "Auth timeout"],
        "roadmap": ["Design DB", "Setup Auth", "Build UI", "Add Tests", "Deploy"],
        "summary": "A robust SaaS application.",
    }
    pdf_bytes = render_blueprint_pdf(sample_blueprint, export_date="2026-03-30")
    assert isinstance(pdf_bytes, bytes)
    assert pdf_bytes.startswith(b"%PDF")
    assert len(pdf_bytes) > 1024  # >1KB for a sample blueprint
    for secret in ["GROQ_API_KEY", "GEMINI_API_KEY", "sk-", "AIza", "gsk_", "eyJ"]:
        assert secret not in pdf_bytes.decode("latin1", errors="ignore")


def test_render_blueprint_pdf_none_values():
    """Assert None values never crash PDF generation."""
    bad_blueprint = {
        "project_name": None,
        "tech_stack": [None, "Python", None],
        "folder_structure": None,
        "edge_cases": None,
        "roadmap": [None],
        "summary": None,
    }
    pdf_bytes = render_blueprint_pdf(bad_blueprint)
    assert isinstance(pdf_bytes, bytes)
    assert pdf_bytes.startswith(b"%PDF")
    content_str = pdf_bytes.decode("latin1", errors="ignore")
    assert "None" not in content_str
