import os
import py_compile

import pytest
from ai_engine import build_pdf_lines, render_blueprint_pdf


def test_v1_6_7_py_compile():
    """Assert app.py and ai_engine.py compile successfully."""
    app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../app.py"))
    engine_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "../ai_engine.py")
    )
    assert py_compile.compile(app_path, doraise=True)
    assert py_compile.compile(engine_path, doraise=True)


def test_red_confirm_buttons_source_scan():
    """Source scan: Confirm buttons in Blueprint library and Engineering Log render with type='primary' and caption absent."""
    app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../app.py"))
    with open(app_path, "r", encoding="utf-8") as f:
        content = f.read()
    assert "Confirming will permanently delete this item." not in content
    assert '"Confirm"' in content
    assert 'type="primary"' in content


def test_auth_branch_render_order_scan():
    """Source scan: auth branch performs all session/Supabase verification before any UI rendering call."""
    app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../app.py"))
    with open(app_path, "r", encoding="utf-8") as f:
        content = f.read()
    verif_block = content.split("Ensure client session is restored")[1].split(
        'user = st.session_state.get("user")'
    )[0]
    for st_call in [
        "st.warning(",
        "st.error(",
        "st.success(",
        "st.info(",
        "st.button(",
    ]:
        assert st_call not in verif_block


def test_build_pdf_lines_no_footer():
    """Assert build_pdf_lines contains no footer string."""
    bp = {
        "project_name": "Test",
        "summary": "Summary",
        "tech_stack": ["Python"],
        "folder_structure": "root/",
        "edge_cases": ["None"],
        "roadmap": ["Step 1"],
    }
    lines = build_pdf_lines(bp)
    for line in lines:
        assert "Generated by CodeBreaker Workspace" not in line


def test_pdf_footer_chrome_and_page1():
    """Source scan & functional check: PDF footer rendered via set_auto_page_break(auto=False) and set_y, page 1 title bold 16 + italic 9 subtitle."""
    engine_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "../ai_engine.py")
    )
    with open(engine_path, "r", encoding="utf-8") as f:
        content = f.read()
    assert "set_auto_page_break(auto=False)" in content
    assert "Generated by CodeBreaker Workspace +" in content
    assert 'pdf.set_font("Helvetica", "B", 16)' in content
    assert 'pdf.set_font("Helvetica", "I", 9)' in content
