import os
import py_compile
import time

import pytest
from ai_engine import build_pdf_lines, render_blueprint_pdf


def test_v1_6_6_py_compile():
    """Assert app.py and ai_engine.py compile successfully."""
    app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../app.py"))
    engine_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "../ai_engine.py")
    )
    assert py_compile.compile(app_path, doraise=True)
    assert py_compile.compile(engine_path, doraise=True)


def test_build_pdf_lines_no_footer():
    """Assert build_pdf_lines no longer appends the footer line."""
    bp = {
        "project_name": "Test Project",
        "summary": "Summary",
        "tech_stack": ["Python"],
        "folder_structure": "root/\n  app.py",
        "edge_cases": ["None"],
        "roadmap": ["Step 1"],
    }
    lines = build_pdf_lines(bp)
    for line in lines:
        assert "Generated by CodeBreaker Workspace" not in line


def test_pdf_footer_and_courier_source_scan():
    """Source scan: render_blueprint_pdf sets footer via set_y on last page and applies Courier for tree."""
    engine_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "../ai_engine.py")
    )
    with open(engine_path, "r", encoding="utf-8") as f:
        content = f.read()
    assert "set_auto_page_break(auto=False)" in content
    assert '"Courier"' in content
    assert "in_folder" in content


def test_sidebar_radio_label_and_no_index():
    """Source scan: st.sidebar.radio has non-empty label, collapsed visibility, and no index parameter."""
    app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../app.py"))
    with open(app_path, "r", encoding="utf-8") as f:
        content = f.read()
    assert "st.sidebar.radio(" in content
    assert 'label_visibility="collapsed"' in content
    radio_chunk = content.split("st.sidebar.radio(")[1].split(")")[0]
    assert "index=" not in radio_chunk


def test_no_n_steps_in_app_and_engine():
    """Source scan: (N Steps) string is completely removed from app.py and ai_engine.py."""
    app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../app.py"))
    engine_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "../ai_engine.py")
    )
    for path in [app_path, engine_path]:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "Steps)" not in content


def test_login_cta_rerun_source_scan():
    """Source scan: landing Log In and Create Account handlers set nav_pending and call st.rerun()."""
    app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../app.py"))
    with open(app_path, "r", encoding="utf-8") as f:
        content = f.read()
    assert "cta_login" in content
    assert "cta_signup" in content
    assert content.count("st.rerun()") > 5


def test_arm_expiry_logic():
    """Assert delete arm expiry logic resets state after 10 seconds for both blueprints and logs."""
    session_state = {
        "arm_del_bp_123": True,
        "arm_time_bp_123": time.time() - 15,
        "confirm_del_log_456": True,
        "arm_time_log_456": time.time() - 15,
    }
    now_t = time.time()
    for k in list(session_state.keys()):
        if k.startswith("arm_time_bp_"):
            b_id = k.replace("arm_time_bp_", "")
            if now_t - session_state.get(k, 0) > 10:
                session_state[f"arm_del_bp_{b_id}"] = False
                session_state.pop(k, None)
        if k.startswith("arm_time_log_"):
            log_id = k.replace("arm_time_log_", "")
            if now_t - session_state.get(k, 0) > 10:
                session_state[f"confirm_del_log_{log_id}"] = False
                session_state.pop(k, None)

    assert session_state["arm_del_bp_123"] is False
    assert "arm_time_bp_123" not in session_state
    assert session_state["confirm_del_log_456"] is False
    assert "arm_time_log_456" not in session_state


def test_confirm_cancel_use_container_width():
    """Source scan: Confirm and Cancel buttons use use_container_width=True in app.py."""
    app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../app.py"))
    with open(app_path, "r", encoding="utf-8") as f:
        content = f.read()
    assert '"Confirm"' in content
    assert '"Cancel"' in content
    assert content.count("use_container_width=True") > 10


def test_na_law_scan():
    """Source scan: asserts no 'Null' fallback literal exists in app.py or ai_engine.py."""
    app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../app.py"))
    engine_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "../ai_engine.py")
    )
    for path in [app_path, engine_path]:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "Null" not in content
        assert "NULL" not in content
