import os
import py_compile

import pytest
from ai_engine import build_pdf_lines, render_blueprint_pdf


def test_v1_6_5_py_compile():
    """Assert app.py and ai_engine.py compile successfully."""
    app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../app.py"))
    engine_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "../ai_engine.py")
    )
    assert py_compile.compile(app_path, doraise=True)
    assert py_compile.compile(engine_path, doraise=True)


def test_build_pdf_lines_no_footer():
    """Assert build_pdf_lines no longer appends the footer line."""
    bp = {
        "project_name": "Test Project",
        "summary": "Summary",
        "tech_stack": ["Python"],
        "folder_structure": "root/\n  app.py",
        "edge_cases": ["None"],
        "roadmap": ["Step 1"],
    }
    lines = build_pdf_lines(bp)
    for line in lines:
        assert "Generated by CodeBreaker Workspace" not in line


def test_pdf_courier_font_source_scan():
    """Source scan: render_blueprint_pdf applies Courier font for folder structure."""
    engine_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "../ai_engine.py")
    )
    with open(engine_path, "r", encoding="utf-8") as f:
        content = f.read()
    assert '"Courier"' in content
    assert "in_folder" in content


def test_sidebar_radio_non_empty_label():
    """Source scan: st.sidebar.radio has non-empty label and no index parameter."""
    app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../app.py"))
    with open(app_path, "r", encoding="utf-8") as f:
        content = f.read()
    assert "st.sidebar.radio(" in content
    assert 'label_visibility="collapsed"' in content
    assert "index=" not in content.split("st.sidebar.radio(")[1].split(")")[0]


def test_no_n_steps_in_app():
    """Source scan: (N Steps) string is completely removed from app.py."""
    app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../app.py"))
    with open(app_path, "r", encoding="utf-8") as f:
        content = f.read()
    assert "Steps)" not in content
