import os
import py_compile

import pytest
from ai_engine import build_pdf_lines, render_blueprint_pdf


def test_v1_6_8_py_compile():
    """Assert app.py and ai_engine.py compile successfully."""
    app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../app.py"))
    engine_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "../ai_engine.py")
    )
    assert py_compile.compile(app_path, doraise=True)
    assert py_compile.compile(engine_path, doraise=True)


def test_v1_6_8_red_confirm_source_scan():
    """Source scan: #c0392b present on Confirm warning banners in app.py."""
    app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../app.py"))
    with open(app_path, "r", encoding="utf-8") as f:
        content = f.read()
    assert content.count("#c0392b") >= 2
    assert '"Confirm"' in content


def test_v1_6_8_pdf_footer_chrome_and_build_lines():
    """Source scan & functional check: set_auto_page_break(auto=False) present and build_pdf_lines has no footer string."""
    engine_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "../ai_engine.py")
    )
    with open(engine_path, "r", encoding="utf-8") as f:
        content = f.read()
    assert "set_auto_page_break(auto=False)" in content
    assert "Generated by CodeBreaker Workspace +" in content

    bp = {
        "project_name": "Test Project",
        "summary": "Summary text",
        "tech_stack": ["Python"],
        "folder_structure": "root/\n  app.py",
        "edge_cases": ["None"],
        "roadmap": ["Step 1"],
    }
    lines = build_pdf_lines(bp)
    for line in lines:
        assert "Generated by CodeBreaker Workspace" not in line


def test_v1_6_8_login_cta_handlers():
    """Source scan: landing CTAs use cta_login and cta_signup with nav_pending and st.rerun()."""
    app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../app.py"))
    with open(app_path, "r", encoding="utf-8") as f:
        content = f.read()
    assert 'key="cta_login"' in content
    assert 'key="cta_signup"' in content
    assert (
        '"nav_pending" = "Auth"' in content
        or "'nav_pending' = 'Auth'" in content
        or '"nav_pending"] = "Auth"' in content
    )
